version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres-tarefas
    restart: always
    environment:
      POSTGRES_DB: todolist_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: sua_senha_forte
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d todolist_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: tarefas-api
    ports:
      - "50:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todolist_db
      SPRING_DATASOURCE_USERNAME: postgres_user
      SPRING_DATASOURCE_PASSWORD: sua_senha_forte

volumes:
  postgres_data:
